M6R0
I-MangTinhToan=6"%&falseGE\[l*%*SolutionwGR6%'%)filenameG%'stringG'%#A1G%$setG'
%#B1GF/6,%"FG%"fG%%AoldG%*sol_foundG%$solG%"AG%"iG%"jG%"DG%#D1GF$F$C)>8$&-%,Rea
dObjectwG6#9$6#""$>8(7">8&<">8)9%@%/-%&minusG6$9&FOFL>8'%%trueG>FWF%?(F$"""FenF
$3/FWF%0FKFNC%>FKFN?(8*FenFen-%%nopsG6#F?FXC$>8%&F?6#F\o@$353/&Fbo6#""#Fen1-F^o
6#-FS6$&FboFEFN&Fbo6#""%3/Fjo""!/-FS6$F`p&Fbo6#""&FL2FhpF^pC%>FN-%&unionG6$FNFb
p>FH7$-%#opG6#FHFbo[@$/-FS6$FUFNFL>FWFX@%FWC%>8,FH?(F\o-F^oFiq!""F$2FhpF\oC%>Fb
o&FHFdo?(8+-F^o6#FcrFfrF$2FhpF\s@$/&Fcr6#F\sFbo>8-7$-Fhq6#&Fcr6#;Fen,&F\sFenFfr
Fen-Fhq6#&Fcr6#;,&F\sFenFenFenF]s@$/-FS6$FU-%)ApQuanheG6$FesFOFL>FcrFes-%'RETUR
NG6#7$FXFcr-F\u6#7$F%FIF$F$F$%)BaodongwGR6$'F3F/'F8F/6(F4%#F1G%'resultGF.%#A2G%
#ffGF$F$C(>FKFL>FWFO>FHFL>FboFD?(F$FenFenF$0FWFHC&>FHFW>FNFL?&F?FboFX@$53/&F?F[
pFhp/-FS6$-FS6$&F?FEFW&F?F]qFL3/F[wFen1-F^o6#F_w&F?FdpC$>FW-Fcq6$FWFaw>FN-Fcq6$
FN<#F?>Fbo-FS6$FboFN-F\u6#FWF$F$F$%)EvalSolwGR6%'F3%%listG'%"HGF/'%"GGF/6+F5%%A
newG%(setlistGF4FiuF9%%bienG%%exprG%)rhs_exprGF$F$C)>F?FO>FK7#F??&FWFDFXC%>Fbo-
Fht6$7#FWF?>FK7$-Fhq6#FKFbo>F?Fbo>FW&FD6#-F^oFC>FH-%&solveG6$-%&parseG6#&FW6#""
'FU?(FN,&FgzFenFfrFenFfrF$2FhpFNC%>FW&FD6#FN>F\o-FS6$&FK6#,&FNFenFenFen&FKFh[l?
&F\sFHFXC&>FH-FS6$FH<#F\s>Fcr-%%subsG6$-Fjz6$F\[lF\o-%$rhsGFcs>F\s/-%$lhsGFcsFc
r>FH-FcqFd\l-F\u6#-%)simplifyGFiqF$F$F$%-Completionw1GR6%F3F[yF]y6.F.Fhu%"SGF4%
#f1G%#ufG%#vfG%"xG%%AtmpG%&Atmp1G%#G1G%&AfterGF$F$C)>8/R6#'F_^lF/6%F]^lF8F5F$F$
C&>FboFD>FKFL?(F$FenFenF$0FboFKC$>FKFbo?&F?T#FX@$0-%*intersectG6$-FS6$FawFbwFbo
FL>Fbo-Fcq6$FboFbw-F\u6#FboF$F$6$FhuFbo>8.FR>F?FO>FboFL>FKFO?&FWFDFXC%@$/-FS6$&
FWFEF?FL@$53/&FWF[pFen0-Fh_l6$F]alFKFL3/FbalFhp/-FS6$&FWF]qFKFLC&@%Faal>FcrFdal
>FcrF[bl>FesFL?&F\sFcrFX@$/-Fh_l6$-FS6$F]alFe\l-Fg^l6#Fe\lFL>Fes-Fcq6$FesFe\l@$
0FesFLC$@'0-Fh_l6$FesFUFL>F\o<#&Fbcl6#Fen0-FSFitFL>F\o<#&FiclFgcl>F\oFL@$0F\oFL
C&>FK-FS6$FKF\o>F[blF\o>FbalFhp>Fbo-Fcq6$Fbo<#FW@$0F[alFL@&5Faal0-FS6$F[blF?FLC
$>F\o<#&F[alFgcl@$0-FS6$F\oFOFLC(>FN-FS6$F]alF\o>FK-Fcq6$FK-FS6$FNF?>F?-Fcq6$F?
F]al>FbalFhp>F[blF\o>FboFgdl0-FS6$F[blFOFLC*>F\oF[bl>FNF[fl?&FHFboFX@$/&FHF]qF\
oC$>Fbo-FS6$Fbo<#FHFjq>FcrF`fl?&F\s-Fh_l6%FNF?-Fg^lFdoFX?&FHFboFX@$/FaglFe\lC%>
Fcr-Fcq6$FcrFe\l>FboFdglFjq>FK-FS6$-Fcq6$FKFcrF\o>F?Fcfl>FboFgdl>Fc`l-FS6$Fc`lF
?-F\u6#7%FKF?FboF$F$F$%,OpSolutionwGR6%F*F[yF]y6/Fix'%&AlistGFjx'%%OpenGF/'%&Cl
oseGF/%&foundG%%nodeGF4F8%)nodelistG%"kGF7%'GetMinG%*Xuly_nextGF$F$C,>Fg^lRF$6$
F\jl%(minnodeGF$F$C&>Fbo&Fd_lFgcl?&F?Fd_lFX@$2F[wFjo>FboF?>Fd_l-FS6$Fd_l<#FboF_
`lF$F$6$FhilFK>80R6$F\jlF46(%&node1G%%AsetG%%BsetG%"gG%'nAlistGF9F$F$C(>FH-F^o6
#Fd_l>Fbo&Fd_l6#&FDFgcl>FK-Fht6$7#FOFbo>F?7#-FhqFC?(FNFenFenFHFX@$/FK&Fd_lFh[lF
jq@%2FHFNC&>FW,&&FDF[pFen&FO6#""(Fen>Fd_l7$-FhqF_\mFK>F?7&,&FHFenFenFenFW&FOFgc
lFc\m>T%-Fcq6$F`^mF`x?&F?F`^mFX@$/&F?FgclFNC$@$2Fc]mF[wC%>F`^m-FSFb^m>F?7&FNFc]
mF^^mFc\m>F`^mFa^mFjqF$F$6&FfilFboFhilFK>F?F@>FboFg\m>FN7&FenFhpFfrFfr>FK<#FN>F
WFL>FHF%?(F$FenFenF$0FKFLC&>FN-Fg^lF$>FW-Fcq6$FWFf_m@$/-FS6$FU&Fbo6#&FNFgclFLC$
>FHFXFjq?&F\oF?FXC$>F\sFe`m@$0-Fht6$7#F\oF\sF\s-Fc[m6$FNF\o@%/FHFXC'>Fcr7#FN?(F
$FenFenF$0Fg`mFenC$>Fes&FNFdp?&FNFWFX@$/Fg`mFesC$>Fcr7$FN-FhqF^sFjq>Fc`lFI?(Fes
F\pFenF]sFXC$>FN&Fcr6#Fes?&F\oF?FX@$/&F\oFgcl&FNFE>Fc`l7$-Fhq6#Fc`lF\o-F\u6#7$F
XFc`lF_uF$F$F$%,CompletionwGRFj]l6*Fh[m%%FsetG%%BaoHGFc^l%#H1GF4%$ansGF^jlF$F$C
*>Fbo-%(convertG6$FDF/>F?FL?&FNFboFX>F?-Fcq6$F?F_cm>F?-FS6$F?-Fcq6$FU-Fbu6$FboF
O>F\oF%>F\sFhp?(F$FenFenF$3/F\oF%1F\sF]oC$?&FH-&%)combinatG6#%'chooseG6$F?F\sFX
C$>FK-Fbu6$Fbo-Fcq6$FOFH@$/-FS6$FUFKFLC$>F\oFXFjq@$0F\oFX>F\sFbt-F\u6#7$F\oFHF$
F$F$FhtR6$'F;FjxFfu6%F`yF9F4F$F$C%>F?FO?(FboFenFenFgzFXC$>FK&FDF``l@$353/&FKF[p
Fen1-F^o6#-FS6$&FKFEF?&FKFdp3/F^hmFhp/-FS6$Fbhm&FKF]qFL2FhpF`hm>F?-Fcq6$F?Fdhm-
F\uF_oF$F$F$FBR6#F*6,%+nameobjectGF3%"MGF4F9%"tG%"mG%"sG%"pG%'helpobGF$F$C*>F\s
-%)readlineGFC>FKFI>FWFI>FHFen>FboFI>FesFI@%/F\sFhp-%&printG6#Q*file~rong6"C,?(
F$FenFenF$/F\sQ!Fjjm>F\sF]jm>F?-F]]l6#-F][lFcs>Fes7$-FhqFjbmF\s>F\sF]jm?(F$FenF
enF$/-%+searchtextG6$Q*variablesFjjmF\sFhp>F\sF]jm>F\sF]jm?(F$FenFenF$/-F[\n6$Q
-endvariablesFjjmF\sFhpC$@$0F\sF^[nC$>FK7$Faz-Fa]lFb[n>FesFe[n>F\sF]jm>F\sF]jm@
$/FKFI-%&ERRORG6#Q-variables=[]Fjjm?(F$FenFenF$0F\sFhpC$@$Fg\n@%2FHFg]mC$@%0FHF
en@%0FHF^q>FW7$-FhqFexFa[n>FW7$Fb^n<#&Fa[nF$>FW7$Fb^nF\s>FHF]^mC&>FHFen>FWFa^n>
Fbo7$-FhqF``lFW>FWFI>F\sF]jm-F\u6#7&F?FKFboFesF$F$F$%&BasewGR6#F36,F.FhuF\^lF4F
]^lF^^lF_^lF`^lFa^lFd^lF$F$C(>FesRFi^lF[_lF$F$C&>FboFD>FKFL?(F$FenFenF$F`_lC$>F
KFbo?&F?Fd_lFX@$Ff_l>FboF]`lF_`lF$F$Fa`l>F?FL>FboFL>FKFL?&FWFDFXC$@$Fj`l@$F_alC
$@%Faal>FcrFdal>FcrF[bl?&F\sFcrFX@$/-Fh_l6$Ffbl-FesFiblFLC'>FK-FS6$FKFe\l>F[blF
e\l>FbalFhp>FboFgdlFjq@$F[el@%F]elC)>F\oFcel>FNF[fl>FKF^fl>F?Fcfl>FbalFhp>F[blF
\o>FboFgdlC*>F\oF[bl>FNF[fl?&FHFboFX@$F`glC$>FboFdglFjq>FcrF`fl?&F\s-Fh_l6%FNF?
-FesFdoFX?&FHFboFX@$F^hlC%>FcrFahl>FboFdglFjq>FKFehl>F?Fcfl>FboFgdlF^ilF$F$F$Fj
jm
